### ISSUE TITLE
Opening BottomSheetMaterialDialog in Adapter from Fragment

### ISSUE THREAD

**Issue by philxws692** [PatilShreyas/MaterialDialog-Android#31]
Hello, 
so basically the question is always in the title...
I wanted to ask how can I build the BottomSheetMaterialDialog in my Adapter which is used in a fragment.
The situation is, that I've got a app, which has got 2 fragments and of the fragments has got a recyclerview with some items and i made a onlongclicklistener onto the layout that works so far. But how can I open the BottomSheetMaterialDialog when I longclick the item. I passed my main activity to the adapter but when I try to open it, the app crashes with the error message 
`java.lang.IllegalStateException: System services not available to Activities before onCreate()`

Seeing forward to your answer 
Thank you
Philipp

**Comment by PatilShreyas** [comment]
I think you're calling `BottomSheetMaterialDialog` before fragment is completely created. If you're using fragment then you should initialize dialog under `onViewCreated()` method of the fragment. It's safe to call it in that method.

Since this isn't related to this library I'm closing this issue. Please use [StackOverflow](https://stackoverflow.com) for such questions.
